pipeline {
    agent any

    parameters {
        string(name: 'stackName', defaultValue: '', description: 'Enter the Stack Name')
        string(name: 'buildNumber', defaultValue: '', description: 'Enter the Build Number')
    }

    environment {
        // API_KEY = credentials('depTrack_local_API_KEY')
        // BASE_URL = credentials('depTrack_local_baseurl')
        // API_KEY = credentials('deptrack_deployed_api_key')
        // BASE_URL = credentials('deptrack_deployed_base_url')
        API_KEY = "ENpnO6nU6JmjXGURJ7weXY7Ig4b9r9u0"
        BASE_URL = "https://dt.secops-corp.cloudera.com/api"
        STACK_NAME = "${params.stackName}"
        BUILD_NUMBER = "${params.buildNumber}"
    }

    stages {
        stage('Start') {
            steps{
                echo 'Start'
            }
        }

        stage('Run') {
            steps {
                sh '''
                    export STACK_NAME=${STACK_NAME}
                    export BUILD_NUMBER=${BUILD_NUMBER}
                    python3 importstack.py
                '''
            }
        }

        stage ('Complete') {
            steps {
                echo 'Completed'
            }
        }
    }
}