pipeline {
    agent any

    environment {
        // API_KEY = credentials('depTrack_local_API_KEY')
        // BASE_URL = credentials('depTrack_local_baseurl')
        API_KEY = credentials('	deptrack_deployed_api_key')
        BASE_URL = credentials('deptrack_deployed_base_url')
        JOB_NAME = "ImportStack"
        USERNAME = credentials('jenkins_username') 
        API_TOKEN = credentials('jenkins_apitoken')
        JENKINS_URL = "http://10.200.5.57:8100"
    }

    stages {
        stage('Start') {
            steps {
                echo 'Start'
            }
        }

        stage('Cleanup') {
            steps{
                sh 'python3 cleanup.py'
            }
        }

        stage('Import All Stacks') {
            steps {
                sh 'python3 importallstacks.py'
            }
        }

        stage ('Complete') {
            steps {
                echo 'Completed'
            }
        }
    }

    
}